#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname "$0")/.."

command_console() {
  echo '```console'
  echo "$ $*"
  "$@"
  echo '```'
}

commands() {
  for cmd in run create-config get-discussion version completion; do
    echo "
## ghd2i $cmd

$(command_console ghd2i help $cmd)"
  done
}

echo "# Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$(command_console ghd2i help)
$(commands)
" > USAGE.md
