---
name: wc-test
on:
  workflow_call:
    secrets:
      gh_app_id:
        required: true
      gh_app_private_key:
        required: true

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod
      - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
        with:
          aqua_version: v2.42.2
      - run: golangci-lint run --timeout 120s
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: go test -v ./... -race -covermode=atomic
      - run: go install ./cmd/ghd2i
      - name: Test help
        run: ghd2i help
      - name: Test version
        run: ghd2i version
      - name: Test version -json
        run: ghd2i version -json
      - name: Test get-discussion
        run: ghd2i get-discussion https://github.com/suzuki-shunsuke/test-ghd2i/discussions/1 > discussions.json
        env:
          GITHUB_TOKEN: ${{github.token}}
      - name: Test get-discussion -query
        run: ghd2i get-discussion -query 'repo:"suzuki-shunsuke/test-ghd2i"'
        env:
          GITHUB_TOKEN: ${{github.token}}

      - name: Test dry run
        run: ghd2i run -repo-name test-ghd2i -data discussions.json -dry-run
        if: |
          !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
        env:
          GITHUB_TOKEN: ${{github.token}}

      - uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: token
        if: |
          !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
        with:
          app_id: ${{secrets.gh_app_id}}
          private_key: ${{secrets.gh_app_private_key}}
          permissions: >-
            {
              "issues": "write"
            }
          repositories: >-
            [
              "test-ghd2i"
            ]
      - name: Test run -data
        run: ghd2i run -data discussions.json
        if: |
          !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: Test run -query
        run: ghd2i run -q 'repo:"suzuki-shunsuke/test-ghd2i"'
        if: |
          !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: Test -lock and -close options
        run: ghd2i run -lock never -close never https://github.com/suzuki-shunsuke/test-ghd2i/discussions/1
        if: |
          !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: Test -lock-discussion and -close-discussion options
        run: ghd2i run -lock-discussion -close-discussion https://github.com/suzuki-shunsuke/test-ghd2i/discussions/102
        if: |
          !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)
        env:
          GITHUB_TOKEN: ${{steps.token.outputs.token}}

      - name: Test create-config
        run: ghd2i create-config
      - run: cat ghd2i.yaml
